In [1]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)
# need more samples to do recursive elimination

In [ ]:
#2.
from sklearn.feature_selection import VarianceThreshold

X = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)
#no value in X meets the threshold condition.. value error

In [3]:
#2.Correct code
from sklearn.feature_selection import VarianceThreshold

X = [[0, 2, 0], [3, 1, 0], [0, 1, 2]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)
X_new

array([[0, 2, 0],
       [3, 1, 0],
       [0, 1, 2]])

In [5]:
#3.
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [0, 0, 0]]
similarity = cosine_similarity(data)
similarity
# error - Cosine similarity is undefined for zero vectors

array([[1., 0.],
       [0., 0.]])

In [5]:
# correct code:
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [1,3,0]]
similarity = cosine_similarity(data)
similarity

array([[1.        , 0.27116307],
       [0.27116307, 1.        ]])

In [6]:
#4.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)
# error: not enough data so the importance ranking might not be accurate

In [ ]:
#5.
data=pd.DataFrame({
    'user' : ['A','B','A'],
    'item' : ['I1','I2', 'I2'],
    'rate' : [5,4,3]
})
pivot =data.pivot(index='user',columns ='item', values='rating')
# import pandas library to use pandas functions
# there is no values relating to 'rating' in the dataframe.. Key error


In [9]:
# correct code
import pandas as pd
data=pd.DataFrame({
    'user' : ['A','B','A'],
    'item' : ['I1','I2', 'I2'],
    'rate' : [5,4,3]
})
pivot =data.pivot(index='user',columns ='item', values='rate')
pivot

item   I1   I2
user          
A     5.0  3.0
B     NaN  4.0

In [ ]:
#6.
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=3)
X_new = pca.fit_transform(X)
# number of components of PCA should be less than the number of features.. here X has 2 and number of components given as 3

In [11]:
# Correct code
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=1)
X_new = pca.fit_transform(X)
X_new

array([[-1.41421356],
       [ 1.41421356]])

In [22]:
#7.

ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})

sim = cosine_similarity(ratings.T)
# need to import pandas library to use pandas functions
# input has None values so can't find pairwise distance

In [13]:
#7.
import pandas as pd
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
ratings_new = ratings.fillna(0)
sim = cosine_similarity(ratings_new.T)
sim

array([[1.        , 0.        , 0.38348249],
       [0.        , 1.        , 0.89442719],
       [0.38348249, 0.89442719, 1.        ]])

In [24]:
#8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


Predicted Score: 2.5


In [25]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


[[0 2]]


In [ ]:
#10.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1])
b = np.array([0, 1, 1])

sim = cosine_similarity(a, b)
print("Similarity:", sim)

# Expected 2d array but there is only one dimension array given(only one sample)

In [15]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1])
b = np.array([0, 1, 1])
a_reshaped=np.array([1,0,1]).reshape(1,-1)
b_reshaped=np.array([0,1,1]).reshape(1,-1)

sim = cosine_similarity(a_reshaped, b_reshaped)
print("Similarity:", sim)

Similarity: [[0.5]]
