In [ ]:
#1. Why does this feature selection with chi2 fail?
from sklearn.feature_selection import SelectKBest, chi2

X = [[-1, 2, 3], [4, 0, -6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [2]:
# Value error: Values of input should be non-negative
# Correct code
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2, 3], [4, 0, 6], [7, 8, 9], [1, 2, 3]]
y = [0, 1, 0, 1]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)


In [3]:
X_new

array([[1, 2],
       [4, 0],
       [7, 8],
       [1, 2]])

In [ ]:
### 2.
from sklearn.metrics.pairwise import cosine_similarity


user1 = ['action', 'comedy', 'romance']
user2 = ['action', 'thriller', 'comedy']

similarity = cosine_similarity([user1], [user2])

# Value error : Could not convert string to float
# To find cosine similarity values should  be numerical

In [4]:
# correct code
from sklearn.metrics.pairwise import cosine_similarity

user1 = [1.5, 2.3, 3.5]
user2 = [4.2, 5.3, 6.4]

similarity = cosine_similarity([user1], [user2])
similarity


array([[0.98721038]])

In [ ]:
#3.
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=5)  
X_new = pca.fit_transform(X)

# value of n_components should be less than X value

In [8]:
# correct code
from sklearn.decomposition import PCA

X = [[1, 2], [3, 4], [5, 6]]
pca = PCA(n_components=2)  
X_new = pca.fit_transform(X)
X_new

array([[-2.82842712e+00, -4.74426853e-17],
       [ 0.00000000e+00, -0.00000000e+00],
       [ 2.82842712e+00, -4.74426853e-17]])

In [14]:
#4.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])


similarity = cosine_similarity(ratings)

# as it contains nan values pairwise distance using cosine_similarity cannot be calculated

array([[1.        , 0.68599434],
       [0.68599434, 1.        ]])

In [16]:
#4.correct code
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

ratings = np.array([[5, 3, np.nan], [4, np.nan, 3]])

ratings_new=np.nan_to_num(ratings,0)
similarity = cosine_similarity(ratings)
similarity

array([[1.        , 0.68599434],
       [0.68599434, 1.        ]])

In [ ]:
#5.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

selector = RFE(estimator=LogisticRegression(), n_features_to_select=5)
selector.fit(X, y) 
# input and output is not defined

In [ ]:
#6.
from sklearn.metrics.pairwise import cosine_similarity

items = ["action movie", "romantic comedy", "sci-fi thriller"]
similarity = cosine_similarity([items[0]], [items[1]])
# pairwise distance cannot be calculated for strings

In [ ]:
#7.
from sklearn.feature_selection import SelectKBest, f_classif

X = [[1, 2], [3, 4], [5, 6]]
y = [0, 1]  
selector = SelectKBest(score_func=f_classif, k=1)
X_new = selector.fit_transform(X, y)
# input values has 3 samples whereas output value as 2 samples

In [ ]:
#8.
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5, 4, 3])
cosine_similarity(ratings, ratings)


In [10]:
#8.Correct code
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

ratings = np.array([5,4,3])
ratings=ratings.reshape(-1,1)
# ratings
cosine_similarity(ratings, ratings)


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#9.
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2], [3, None], [4, 5]]
y = [0, 1, 0]

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)
# Input has none value

In [12]:
# Correct code
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, chi2

X = [[1, 2], [3, 4], [4, 5]]
y = [0, 1, 0]

pipeline = Pipeline([
    ('select', SelectKBest(score_func=chi2, k=1))
])

pipeline.fit(X, y)

Pipeline(steps=[('select',
                 SelectKBest(k=1,
                             score_func=<function chi2 at 0x00000168A946DB20>))])

In [ ]:
#10.
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, -1, 3], [0, 2, 1], [3, -1, 0]])
y = [0, 1, 0]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)
# error: INput should be non-negative

In [1]:
# Correct codez
from scipy.sparse import csr_matrix
from sklearn.feature_selection import SelectKBest, chi2

X = csr_matrix([[0, 1, 3], [0, 2, 1], [3, 1, 0]])
y = [0, 1, 0]

selector = SelectKBest(score_func=chi2, k=2)
X_new = selector.fit_transform(X, y)